catalog:
  name: Oito Web Apps
  version: v1.0.0
  minimum_rancher_version: v1.5.0-rc1

services:
  nginxlb:
    scale: 3
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: mynginx
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  mynginx:
    start_on_create: true
